### PR TITLE
Clean project

### PR DESCRIPTION
**Pull request by Its-Just-Nans**
Hello

Here is a Pull request that clean the project:

- delete useless files `__pycache__`, `.firebase`
- update the python script to be **multiplaform** and **using multiprocess**
- update README accordingly to changes

### CODE REVIEW

**Comment by ICEREG1992** [comment]
Also switches to CDN for leaflet js and css. Will test new Python script then merge, thank you for your contribution!!

**Comment by ICEREG1992** [comment]
Multiprocessing is not working as expected. Hitting a similar issue to <https://stackoverflow.com/a/65001152>, switching to the `multiprocess` library as the answer suggests fixes my issues. If there's a prerequisite step to get this working with `multiprocessing`, please include it in the readme.

Otherwise, the PR looks really good. We should probably say that calling `python HelperTools.py` will generate tilesets for **every map in .\maps** rather than implying it will do the same thing as `ImageToTileset(r"[path to your png map]", r"[directory you want the tileset to be placed]")` which just converts one map to a directory of the user's choosing. Let me know if you'd prefer that I make that change to the readme.

**Comment by Its-Just-Nans** [comment]
Hi

Thanks for comments. I moved `wrapper_to_tileset()` to public (not in `if __name__ == "__main__":`) could you retry your test ?

On my side, on Linux, it's working, are you using Windows ?

If it still not working, I will update the script with `multiprocess` I guess

Also fixed the README

**Comment by ICEREG1992** [comment]
I'm on Windows, yeah. The script is working great after the update! Merging.

**Pull request merged**
